### ISSUE TITLE
Private wishlists are viewable

### ISSUE THREAD

**Issue by brchristian** [boomerdigital/solidus_wishlist#12]
Our store is looking at migrating from our own custom fork of `spree-contrib/spree_wishlist` to this one because of how well it seems to be maintained. One thing we noticed is that despite the fact that wishlists have an `is_private` attribute, and there is a `Spree::Wishlist#can_be_read_by?` method, nonetheless all wishlists are viewable. Namely, when logged out, one can visit the URL of any private wishlist and see what it contains.

If there is interest from the maintainers, I would be happy to prepare a PR including a test and a fix for this. I would imagine that we’d want to return either a 401 or a 404 code if the list is private and the user accessing it isn’t the owner.

Let me know what you think. Cheers!

**Comment by mtomov** [comment]
Having a PR is just great. Thanks!

**Comment by brchristian** [comment]
@mtomov I’ve just added the failing pecs and a simple fix to add authentication to the wishlists controller at https://github.com/boomerdigital/solidus_wishlist/pull/15. Cheers!
